# Generated by Django 6.1 on 2026-08-22 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('goal', models.CharField(blank=True, default='', max_length=120)),
                ('track', models.CharField(choices=[('11 month', '11 month'), ('17 month', '17 month')], default='11 month', max_length=16)),
                ('program', models.CharField(default='MSBA', max_length=120)),
                ('standing', models.CharField(choices=[('onTrack', 'onTrack'), ('watch', 'watch'), ('needsHelp', 'needsHelp')], default='onTrack', max_length=16)),
                ('standing_summary', models.CharField(default="You're on track.", max_length=240)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('current_term', models.CharField(default='Fall 2026', max_length=40)),
                ('program_start', models.DateField()),
                ('consent_calendar_read', models.BooleanField(default=False)),
                ('consent_lms_read', models.BooleanField(default=False)),
                ('consent_career_recommendations', models.BooleanField(default=False)),
                ('consent_advisor_sharing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thrive_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
