# Generated by Django 6.1 on 2026-08-22 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=120)),
                ('term', models.CharField(max_length=40)),
                ('units', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rsm_thrive.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=120)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='rsm_thrive.course')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('grade_breakdown', models.JSONField(default=list)),
                ('policies', models.JSONField(default=list)),
                ('office_hours', models.CharField(default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='')),
                ('last_updated', models.DateField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='rsm_thrive.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('standing', models.CharField(choices=[('onTrack', 'onTrack'), ('watch', 'watch'), ('needsHelp', 'needsHelp')], default='onTrack', max_length=16)),
                ('current_grade', models.CharField(blank=True, default='', max_length=16)),
                ('nudge', models.CharField(blank=True, default='', max_length=240)),
                ('bucket', models.CharField(choices=[('core', 'core'), ('elective', 'elective')], default='core', max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsm_thrive.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uniq_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not-started', 'not-started'), ('in-progress', 'in-progress'), ('submitted', 'submitted'), ('graded', 'graded'), ('late', 'late')], default='not-started', max_length=16)),
                ('grade', models.CharField(blank=True, default='', max_length=16)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsm_thrive.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'assignment'), name='uniq_student_assignment')],
            },
        ),
    ]
