# Generated by Django 6.1 on 2026-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0002_course_assignment_coursemeeting_syllabus_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('rady', 'rady'), ('ucsd', 'ucsd'), ('sandiego', 'sandiego'), ('club', 'club'), ('career', 'career')], default='rady', max_length=16)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('register_url', models.URLField(blank=True, default='')),
                ('goal_tags', models.JSONField(default=list)),
            ],
        ),
    ]
