# Generated by Django 6.1 on 2026-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('academic', 'academic'), ('career', 'career'), ('wellness', 'wellness'), ('technical', 'technical'), ('administrative', 'administrative')], max_length=20)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
    ]
