# Generated by Django 6.1 on 2026-08-22 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0006_calendarprefs_eventjoin_ignoredevent_tasknote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('11 month', '11 month'), ('17 month', '17 month')], max_length=16, unique=True)),
                ('units_required', models.PositiveSmallIntegerField()),
                ('core_required', models.PositiveSmallIntegerField()),
                ('elective_required', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('detail', models.CharField(default='', max_length=400)),
                ('severity', models.CharField(choices=[('onTrack', 'onTrack'), ('watch', 'watch'), ('needsHelp', 'needsHelp')], default='watch', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPhaseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('11 month', '11 month'), ('17 month', '17 month')], max_length=16)),
                ('phase_id', models.CharField(choices=[('orientation', 'orientation'), ('fall', 'fall'), ('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer'), ('optional-fall', 'optional-fall')], max_length=16)),
                ('label', models.CharField(max_length=60)),
                ('term', models.CharField(max_length=40)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('optional', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.UniqueConstraint(fields=('track', 'phase_id'), name='uniq_phase_per_track')],
            },
        ),
    ]
