# Generated by Django 6.1 on 2026-08-22 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0007_degreerequirement_degreegap_programphaserow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('service', models.CharField(choices=[('advising', 'advising'), ('career', 'career')], max_length=16)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('location', models.CharField(max_length=200)),
                ('blurb', models.CharField(blank=True, default='', max_length=240)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='confirmed', max_length=16)),
                ('zoom_join_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('zoom', 'zoom'), ('email_request', 'email_request'), ('email_cancel', 'email_cancel')], max_length=16)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('failed', 'failed'), ('skipped', 'skipped')], max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rsm_thrive.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('mode', models.CharField(choices=[('in person', 'in person'), ('zoom', 'zoom')], default='zoom', max_length=16)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='rsm_thrive.advisor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rsm_thrive.appointmentslot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('slot',), name='uniq_confirmed_slot'),
        ),
    ]
