# Generated by Django 6.1 on 2026-08-23 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0010_conversation_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='client_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='studenttask',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key__isnull', False)), fields=('user', 'client_key'), name='uniq_student_task_client_key'),
        ),
    ]
