# Generated by Django 6.1 on 2026-08-23 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0011_studenttask_client_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItemLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=120)),
                ('label', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'item_key'), name='uniq_item_label')],
            },
        ),
        migrations.CreateModel(
            name='CalendarItemUrgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'item_key'), name='uniq_item_urgent')],
            },
        ),
        migrations.CreateModel(
            name='CustomCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('day_key', models.CharField(max_length=10)),
                ('time', models.CharField(blank=True, default='', max_length=5)),
                ('label', models.TextField(blank=True, default='')),
                ('urgent', models.BooleanField(default=False)),
                ('created_at_ms', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_custom_event')],
            },
        ),
        migrations.CreateModel(
            name='QuickListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_at_ms', models.BigIntegerField()),
                ('copied_from', models.CharField(blank=True, default='', max_length=120)),
                ('due_date', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_quick_item')],
            },
        ),
    ]
