# Generated by Django 6.1 on 2026-08-23 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0012_calendaritemlabel_calendaritemurgent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('syllabus', 'syllabus'), ('policy', 'policy'), ('catalog', 'catalog'), ('scraped', 'scraped')], max_length=16)),
                ('destinations', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rsm_thrive.document')),
            ],
            options={
                'ordering': ['document_id', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('document', 'seq'), name='uniq_document_chunk_seq')],
            },
        ),
    ]
