# Generated by Django 6.1 on 2026-08-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0013_document_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTurnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=16)),
                ('model_note', models.CharField(max_length=32)),
                ('chunk_ids', models.JSONField(default=list)),
                ('duration_ms', models.IntegerField(default=0)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turn_log', to='rsm_thrive.chatmessage')),
            ],
        ),
    ]
