# Generated by Django 6.1 on 2026-08-23 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0014_chatturnlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('skills', models.JSONField(default=list)),
                ('embedding', models.JSONField(default=list)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_job_source_external')],
            },
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(choices=[('strong', 'strong'), ('good', 'good'), ('stretch', 'stretch'), ('reach', 'reach')], max_length=16)),
                ('score', models.IntegerField()),
                ('matched_skills', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('verdict', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rsm_thrive.jobposting')),
                ('resume_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsm_thrive.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'posting', 'resume_version'), name='uniq_match_report')],
            },
        ),
    ]
