# Generated by Django 6.1 on 2026-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0016_postinginteraction_jobposting_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
