# Generated by Django 6.1 on 2026-08-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0018_courseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='track',
            field=models.CharField(blank=True, choices=[('11 month', '11 month'), ('17 month', '17 month')], default='', max_length=16),
        ),
    ]
