# Generated by Django 6.1 on 2026-08-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0019_alter_courseplan_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner_session', to='rsm_thrive.conversation')),
            ],
        ),
    ]
