# Generated by Django 6.1 on 2026-08-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0020_plannersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannersession',
            name='review',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
