# Generated by Django 6.1 on 2026-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0021_plannersession_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='quick_replies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
