# Generated by Django 6.1 on 2026-08-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0022_chatmessage_quick_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='form',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
