# Generated by Django 6.1 on 2026-09-02 00:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0023_chatmessage_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=8)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatturnlog',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='chatturnlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatturnlog',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatturnlog',
            name='refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatturnlog',
            name='route',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='chatturnlog',
            name='route_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatturnlog',
            index=models.Index(fields=['-created_at'], name='rsm_thrive__created_44be39_idx'),
        ),
        migrations.AddIndex(
            model_name='chatturnlog',
            index=models.Index(fields=['refused', '-created_at'], name='rsm_thrive__refused_456d28_idx'),
        ),
        migrations.AddIndex(
            model_name='chatturnlog',
            index=models.Index(fields=['route', '-created_at'], name='rsm_thrive__route_7e838a_idx'),
        ),
        migrations.AddField(
            model_name='turnfeedback',
            name='turn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='rsm_thrive.chatturnlog'),
        ),
        migrations.AddField(
            model_name='turnfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='turnfeedback',
            index=models.Index(fields=['rating', '-updated_at'], name='rsm_thrive__rating_259a3e_idx'),
        ),
    ]
