# Generated by Django 6.1 on 2026-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0025_backfill_turn_log_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannersession',
            name='situation',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
