# Generated by Django 6.1 on 2026-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0026_plannersession_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannersession',
            name='asked',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
