# Generated by Django 6.1 on 2026-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0028_console_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'content management',
                'verbose_name_plural': 'Content management',
                'managed': False,
            },
        ),
    ]
