# Generated by Django 6.1 on 2026-09-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0029_contenttool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReview',
            fields=[
            ],
            options={
                'verbose_name': 'answer review',
                'verbose_name_plural': 'Answer review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rsm_thrive.chatturnlog',),
        ),
        migrations.CreateModel(
            name='AnswerCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='rsm_thrive.chatturnlog')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
