# Generated by Django 6.1 on 2026-09-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm_thrive', '0030_answerreview_answercorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'Operations',
                'managed': False,
            },
        ),
    ]
