# Generated by Django 6.1 on 2026-09-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rsm_thrive", "0032_advisorcalendarconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("zoom", "zoom"),
                    ("email_request", "email_request"),
                    ("email_cancel", "email_cancel"),
                    ("graph_event", "graph_event"),
                ],
                max_length=16,
            ),
        ),
    ]
