from django.urls import path

from .views import advisors, appointments, assignments, auth, chat, courses, degree, events, health, jobs, overlay, personal, planner, requests, resources, resume, students, tasks

app_name = "rsm_thrive"

urlpatterns = [
    path("advisors", advisors.advisors, name="advisors"),
    path("advisors/<str:advisor_id>/slots", advisors.advisor_slots, name="advisor-slots"),
    path("appointments", appointments.appointments_dispatch, name="appointments"),
    path("appointments/<str:appointment_id>/cancel", appointments.cancel_appointment, name="appointment-cancel"),
    path("assignments", assignments.assignments, name="assignments"),
    path("calendar-items/<str:item_key>/label", personal.item_label, name="calendar-item-label"),
    path("calendar-items/<str:item_key>/urgent", personal.item_urgent, name="calendar-item-urgent"),
    path("calendar-prefs", overlay.calendar_prefs, name="calendar-prefs"),
    path("conversations", chat.conversations, name="conversations"),
    path("conversations/<str:conversation_id>/messages",
         chat.conversation_messages, name="conversation_messages"),
    path("conversations/<str:conversation_id>", chat.conversation, name="conversation"),
    path("courses", courses.courses, name="courses"),
    path("custom-events/<str:key>", personal.custom_event, name="custom-event"),
    path("degree/progress", degree.progress, name="degree-progress"),
    path("degree/timeline", degree.timeline, name="degree-timeline"),
    path("dev-login", auth.dev_login, name="dev-login"),
    path("events", events.events, name="events"),
    path("events/<str:event_id>/ignore", overlay.ignore_event, name="event-ignore"),
    path("events/<str:event_id>/join", overlay.join_event, name="event-join"),
    path("health", health.health, name="health"),
    path("jobs", jobs.jobs_search, name="jobs-search"),
    path("jobs/feed", jobs.jobs_feed, name="jobs-feed"),
    path("jobs/<str:job_id>", jobs.job_detail, name="job-detail"),
    path("jobs/<str:job_id>/dismiss", jobs.job_dismiss, name="job-dismiss"),
    path("jobs/<str:job_id>/like", jobs.job_like, name="job-like"),
    path("jobs/<str:job_id>/report", jobs.job_report, name="job-report"),
    path("me", students.me, name="me"),
    path("overlay", overlay.overlay, name="overlay"),
    path("requests/prefill", requests.prefill, name="request-prefill"),
    path("requests", requests.requests_dispatch, name="requests"),
    path("requests/<str:request_id>/submit", requests.submit_request, name="request-submit"),
    path("plan", planner.plan, name="plan"),
    path("plan/intake", planner.intake, name="plan-intake"),
    path("plan/alternatives", planner.alternatives, name="plan-alternatives"),
    path("plan/swap", planner.swap, name="plan-swap"),
    path("quick-items/<str:key>", personal.quick_item, name="quick-item"),
    path("resources", resources.resources, name="resources"),
    path("resume/current", resume.resume_current, name="resume-current"),
    path("resume/skills", resume.skills, name="resume-skills"),
    path("resume/upload", resume.resume_upload, name="resume-upload"),
    path("resume/versions", resume.resume_versions_dispatch, name="resume-versions"),
    path("resume/versions/<str:version_id>/current", resume.set_current_version, name="resume-set-current"),
    path("syllabi", courses.syllabi, name="syllabi"),
    path("tasks", tasks.tasks_dispatch, name="tasks"),
    path("tasks/order", tasks.bulk_order, name="tasks-order"),
    path("tasks/<str:task_id>", tasks.delete_task, name="task-delete"),
    path("tasks/<str:task_id>/note", overlay.task_note, name="task-note"),
    path("tasks/<str:task_id>/override", tasks.override, name="task-override"),
    path("tss", requests.tss, name="tss"),
    path("tss/connect", requests.tss_connect, name="tss-connect"),
]
